import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useEffect, useMemo } from "react";
import { Nav } from "../components/Nav";
import { Footer } from "../components/Footer";
import {
  Search,
  BookOpen,
  Sparkles,
  Zap,
  BatteryCharging,
  Wrench,
  ShieldCheck,
  ArrowRight,
  ChevronRight,
  FilterX,
  Bot,
  SlidersHorizontal,
  ArrowUpRight,
} from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/blog")({
  component: BlogPage,
});

interface BlogPost {
  id: string;
  title: string;
  category: string;
  readTime: string;
  date: string;
  excerpt: string;
  author: string;
  img: string;
  featured?: boolean;
}

const CATEGORIES = [
  "All",
  "Maintenance",
  "Troubleshooting",
  "Battery Care",
  "How-to Guides",
  "Tips & Tricks",
];

const SAMPLE_POSTS: BlogPost[] = [
  {
    id: "post-1",
    title: "5 Critical Signs Your EV Battery Cell Needs Active Balancing",
    category: "Battery Care",
    readTime: "5 min read",
    date: "Aug 14, 2026",
    excerpt:
      "Learn how capacity drift occurs in lithium-ion battery packs and how Autobot OS cell-level balancing restores original range.",
    author: "Autobot Technical Team",
    img: "https://images.unsplash.com/photo-1558441719-2347b7341ed2?w=800&auto=format&fit=crop&q=80",
    featured: true,
  },
  {
    id: "post-2",
    title: "How to Maximize Ola & Ather Range During Peak Indian Summers",
    category: "Tips & Tricks",
    readTime: "4 min read",
    date: "Aug 10, 2026",
    excerpt:
      "Essential thermal management practices to prevent BMS throttling and preserve battery health in 40°C+ ambient temperatures.",
    author: "Rajesh Kumar, Senior EV Diagnostics",
    img: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: "post-3",
    title: "Step-by-Step Guide: Troubleshooting BLDC Hub Motor Noise",
    category: "Troubleshooting",
    readTime: "7 min read",
    date: "Aug 05, 2026",
    excerpt:
      "Diagnosing bearing wear, hall sensor misalignment, and phase wire shorts before controller breakdown occurs.",
    author: "Autobot Technical Team",
    img: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: "post-4",
    title: "EV Periodic Maintenance Checklist: 32 Points Every Owner Should Know",
    category: "Maintenance",
    readTime: "6 min read",
    date: "Jul 28, 2026",
    excerpt:
      "From brake fluid moisture testing to CAN-bus diagnostic error code scans: a complete guide to preventive EV care.",
    author: "Priya Sharma, Lead Quality Audit",
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: "post-5",
    title: "How to Read BMS Diagnostic Telemetry Reports Like a Pro",
    category: "How-to Guides",
    readTime: "5 min read",
    date: "Jul 20, 2026",
    excerpt:
      "Understanding delta voltage, cell internal resistance (mΩ), and state-of-health (SOH) graphs generated by AI diagnostic hubs.",
    author: "Autobot Technical Team",
    img: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80",
  },
];

function BlogPage() {
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [researchQuery, setResearchQuery] = useState("");
  const [emailInput, setEmailInput] = useState("");

  const [siteTheme, setSiteTheme] = useState<"dark" | "light">(() => {
    if (
      typeof document !== "undefined" &&
      document.documentElement.classList.contains("theme-light")
    ) {
      return "light";
    }
    return "dark";
  });

  useEffect(() => {
    if (typeof document === "undefined") return;

    const checkTheme = () => {
      const isLight = document.documentElement.classList.contains("theme-light");
      setSiteTheme(isLight ? "light" : "dark");
    };

    checkTheme();

    const observer = new MutationObserver(checkTheme);
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class"],
    });

    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const filteredPosts = useMemo(() => {
    return SAMPLE_POSTS.filter((post) => {
      const matchesCategory =
        selectedCategory === "All" || post.category === selectedCategory;
      const query = searchQuery.toLowerCase().trim();
      const matchesSearch =
        !query ||
        post.title.toLowerCase().includes(query) ||
        post.excerpt.toLowerCase().includes(query) ||
        post.category.toLowerCase().includes(query);

      return matchesCategory && matchesSearch;
    });
  }, [selectedCategory, searchQuery]);

  const clearFilters = () => {
    setSelectedCategory("All");
    setSearchQuery("");
  };

  const handleResearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!researchQuery) return;
    toast.success(`Searching ecosystem for "${researchQuery}"...`);
  };

  const handleNewsletterSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!emailInput) return;
    toast.success(`Subscribed ${emailInput} to EV Care Weekly Newsletter!`);
    setEmailInput("");
  };

  const isLight = siteTheme === "light";

  return (
    <div
      className={`min-h-screen font-sans transition-colors duration-500 overflow-x-hidden ${
        isLight
          ? "bg-[#f4f8f5] text-[#1a2320] selection:bg-[#00D084] selection:text-black"
          : "bg-[#020503] text-white selection:bg-[#00D084] selection:text-black"
      }`}
    >
      {/* Navigation */}
      <Nav />

      {/* =========================================================================
          1. HERO HEADER SECTION WITH CUSTOM HERO BACKGROUND IMAGE
         ========================================================================= */}
      <section
        className={`relative pt-28 pb-16 px-6 lg:px-12 rounded-b-[48px] overflow-hidden border-b transition-colors duration-500 ${
          isLight ? "bg-[#0c140e] border-black/10" : "bg-[#020503] border-white/10"
        }`}
      >
        {/* Uploaded Blog Hero Background Image - 100% Raw Clarity */}
        <img
          src="/blog-hero-bg.png"
          alt="EV Blog Background"
          className="absolute inset-0 w-full h-full object-cover object-center opacity-100 pointer-events-none"
        />

        <div className="max-w-7xl mx-auto relative z-10 py-12">
          {/* Main Hero Headline (Bold & Clean - "Hey We're" Removed as requested) */}
          <div className="max-w-3xl space-y-6 text-left">
            <h1 className="text-5xl sm:text-7xl lg:text-8xl font-sans font-black tracking-[-0.04em] !text-white leading-[0.95] drop-shadow-[0_4px_25px_rgba(0,0,0,0.9)]">
              EV Tech &amp; <br />
              Diagnostic <br />
              Experts
            </h1>
          </div>
        </div>
      </section>

      {/* =========================================================================
          2. TRUSTED PARTNERS / FEATURED IN BAR (LIGHT/DARK THEME ADAPTIVE)
         ========================================================================= */}
      <section className="py-8 px-6 max-w-7xl mx-auto">
        <div
          className={`border rounded-[32px] p-6 sm:p-8 flex flex-col md:flex-row items-center justify-between gap-6 text-left transition-colors duration-300 ${
            isLight
              ? "bg-white border-[#d6e3da] text-[#1a2320] shadow-md"
              : "bg-[#0b120d] border-white/10 text-white"
          }`}
        >
          <div
            className={`text-xs sm:text-sm font-sans font-semibold tracking-[-0.04em] shrink-0 ${
              isLight ? "text-[#4a5851]" : "text-white/60"
            }`}
          >
            Trusted by EV Owners &amp; Fleets Across India
          </div>

          <div
            className={`flex flex-wrap items-center justify-center md:justify-end gap-6 sm:gap-10 transition-all duration-300 ${
              isLight ? "text-[#1a2320]" : "text-white/80"
            }`}
          >
            <span className="text-sm font-sans font-extrabold tracking-widest">OLA ELECTRIC</span>
            <span className="text-sm font-sans font-extrabold tracking-widest">ATHER ENERGY</span>
            <span className="text-sm font-sans font-extrabold tracking-widest">TVS iQUBE</span>
            <span className="text-sm font-sans font-extrabold tracking-widest">BAJAJ CHETAK</span>
            <span className="text-sm font-sans font-extrabold tracking-widest">HERO VIDA</span>
          </div>
        </div>
      </section>

      {/* =========================================================================
          3. OUR APPROACH SECTION (LIGHT/DARK THEME ADAPTIVE)
         ========================================================================= */}
      <section
        className={`py-16 px-6 lg:px-12 max-w-7xl mx-auto border-b transition-colors duration-500 ${
          isLight ? "border-black/10" : "border-white/10"
        }`}
      >
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-end">
          
          {/* Left Column: Heading */}
          <div className="lg:col-span-7 space-y-4 text-left">
            <span className="text-[#00D084] text-sm font-sans font-semibold tracking-wide block">
              Our Approach
            </span>

            <h2
              className={`text-4xl sm:text-6xl font-sans font-bold tracking-[-0.04em] leading-[1.05] ${
                isLight ? "text-[#1a2320]" : "text-white"
              }`}
            >
              Smart Strategies <br />
              Real Diagnostic Results <br />
              Meaningful Range Growth
            </h2>
          </div>

          {/* Right Column: Paragraph + Green Pill CTA */}
          <div className="lg:col-span-5 space-y-6 text-left">
            <p
              className={`text-sm sm:text-base font-sans font-light leading-relaxed ${
                isLight ? "text-[#4a5851]" : "text-white/70"
              }`}
            >
              We combine deep diagnostic telemetry, certified mechanic expertise, and preventive maintenance guides to help your electric vehicle run at peak efficiency sustainably.
            </p>

            <form onSubmit={handleNewsletterSubmit} className="flex flex-col sm:flex-row items-center gap-3">
              <input
                type="email"
                required
                placeholder="Enter your email for insights..."
                value={emailInput}
                onChange={(e) => setEmailInput(e.target.value)}
                className={`w-full sm:w-auto flex-1 border rounded-full px-5 py-3 text-xs font-sans focus:outline-none focus:border-[#00D084] ${
                  isLight
                    ? "bg-white border-[#c5d6ca] text-[#1a2320] placeholder-[#607267]"
                    : "bg-[#09110c] border-white/20 text-white placeholder-white/40"
                }`}
              />
              <button
                type="submit"
                className="w-full sm:w-auto px-6 py-3 rounded-full bg-[#00D084] text-[#020403] text-xs font-sans font-black uppercase tracking-wider flex items-center justify-center gap-2 hover:bg-[#00e08f] transition-all cursor-pointer shrink-0 shadow-[0_0_20px_rgba(0,208,132,0.3)]"
              >
                <span>Subscribe Now</span>
                <div className="w-5 h-5 rounded-full bg-[#020403] flex items-center justify-center text-[#00D084]">
                  <ArrowRight className="w-3 h-3" />
                </div>
              </button>
            </form>
          </div>

        </div>
      </section>

      {/* =========================================================================
          4. MAIN ARTICLES ARCHIVE (WITH LIGHT/DARK THEME ADAPTIVE CARDS)
         ========================================================================= */}
      <section id="blog-archive" className="py-20 px-6 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          
          {/* Main Articles Area (8 cols) */}
          <div className="lg:col-span-8 space-y-8 text-left">
            
            {/* Category Filter Pills & Search Input */}
            <div className="space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div className="flex flex-wrap items-center gap-2">
                  {CATEGORIES.map((cat) => (
                    <button
                      key={cat}
                      onClick={() => setSelectedCategory(cat)}
                      className={`px-4 py-2 rounded-full text-xs font-sans font-semibold uppercase transition-all cursor-pointer border ${
                        selectedCategory === cat
                          ? "bg-[#00D084] text-[#020403] border-[#00D084]"
                          : isLight
                          ? "bg-white text-[#1a2320] border-[#c5d6ca] hover:border-[#00D084]"
                          : "bg-[#070e0a] text-white/70 border-white/10 hover:border-white/20 hover:text-white"
                      }`}
                    >
                      {cat}
                    </button>
                  ))}
                </div>

                <div
                  className={`text-xs font-sans ${
                    isLight ? "text-[#607267]" : "text-white/50"
                  }`}
                >
                  Articles ({filteredPosts.length})
                </div>
              </div>

              {/* Instant Search Bar */}
              <div className="relative">
                <Search className="w-4 h-4 text-[#00D084] absolute left-4 top-3.5" />
                <input
                  type="text"
                  placeholder="Filter articles by keyword (e.g., BMS, Ather, Motor, Noise)..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className={`w-full border rounded-full pl-11 pr-4 py-3 text-xs font-sans focus:outline-none focus:border-[#00D084] ${
                    isLight
                      ? "bg-white border-[#c5d6ca] text-[#1a2320] placeholder-[#607267]"
                      : "bg-[#070e0a] border-white/15 text-white placeholder-white/40"
                  }`}
                />
              </div>
            </div>

            {/* Articles Grid */}
            {filteredPosts.length > 0 ? (
              <div className="space-y-6">
                {filteredPosts.map((post) => (
                  <article
                    key={post.id}
                    className={`border rounded-[32px] p-6 transition-all duration-300 group flex flex-col md:flex-row gap-6 items-start ${
                      isLight
                        ? "bg-white border-[#d6e3da] text-[#1a2320] shadow-sm hover:border-[#00D084]"
                        : "bg-[#080f0b] border-white/10 text-white shadow-xl hover:border-[#00D084]/50"
                    }`}
                  >
                    <img
                      src={post.img}
                      alt={post.title}
                      className="w-full md:w-52 h-40 object-cover rounded-2xl shrink-0 group-hover:scale-102 transition-transform duration-500"
                    />

                    <div className="space-y-3 flex-1">
                      <div className="flex items-center justify-between text-xs font-sans">
                        <span className="text-[#00D084] font-sans font-bold uppercase tracking-wider">
                          {post.category}
                        </span>
                        <span className={isLight ? "text-[#607267]" : "text-white/50"}>
                          {post.date} • {post.readTime}
                        </span>
                      </div>

                      <h3
                        className={`text-xl font-sans font-bold group-hover:text-[#00D084] transition-colors leading-snug ${
                          isLight ? "text-[#1a2320]" : "text-white"
                        }`}
                      >
                        {post.title}
                      </h3>

                      <p
                        className={`text-xs font-sans font-light leading-relaxed ${
                          isLight ? "text-[#4a5851]" : "text-white/60"
                        }`}
                      >
                        {post.excerpt}
                      </p>

                      <div className="flex items-center justify-between pt-2">
                        <span
                          className={`text-[11px] font-sans italic ${
                            isLight ? "text-[#607267]" : "text-white/40"
                          }`}
                        >
                          By {post.author}
                        </span>
                        <button
                          onClick={() => toast.info(`Opening article: "${post.title}"`)}
                          className="text-xs font-sans font-bold text-[#00D084] hover:underline flex items-center gap-1 cursor-pointer"
                        >
                          Read Article <ChevronRight className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>
                  </article>
                ))}
              </div>
            ) : (
              /* No Articles Found State */
              <div
                className={`border rounded-[32px] p-12 text-center space-y-4 ${
                  isLight
                    ? "bg-white border-[#d6e3da] text-[#1a2320]"
                    : "bg-[#070e0a] border-white/10 text-white"
                }`}
              >
                <div className="w-12 h-12 rounded-full bg-black/5 border border-black/10 flex items-center justify-center mx-auto text-black/40">
                  <FilterX className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-sans font-bold">
                  No articles found matching your criteria.
                </h3>
                <p className="text-xs opacity-75 font-sans font-light">
                  Try clearing your category filters or search query to view all technical guides.
                </p>
                <button
                  onClick={clearFilters}
                  className="px-6 py-2.5 rounded-full bg-[#00D084] text-[#020403] text-xs font-sans font-black uppercase tracking-wider hover:bg-[#00e08f] transition-all cursor-pointer"
                >
                  Clear filters
                </button>
              </div>
            )}
          </div>

          {/* Sidebar Area (4 cols) */}
          <div className="lg:col-span-4 space-y-8 text-left">
            
            {/* My EV Services AI Analyzer Card */}
            <div
              className={`border-2 border-[#00D084] rounded-[32px] p-6 space-y-4 relative overflow-hidden ${
                isLight ? "bg-white shadow-md" : "bg-[#06110a]"
              }`}
            >
              <div className="space-y-1">
                <span className="text-xs font-sans font-bold text-[#00D084] uppercase tracking-widest block">
                  My EV Services AI
                </span>
                <h3
                  className={`text-2xl font-sans font-bold tracking-[-0.04em] ${
                    isLight ? "text-[#1a2320]" : "text-white"
                  }`}
                >
                  Analyze your vehicle
                </h3>
              </div>

              <p
                className={`text-xs font-sans font-light leading-relaxed ${
                  isLight ? "text-[#4a5851]" : "text-white/70"
                }`}
              >
                If you’re signed in, pick your saved EV and get a weakness checklist.
              </p>

              <button
                onClick={() => toast.info("Opening AI vehicle analysis login flow...")}
                className="w-full py-3 rounded-full bg-[#00D084] text-[#020403] text-xs font-sans font-black uppercase tracking-widest hover:bg-[#00e08f] transition-all cursor-pointer flex items-center justify-center gap-2"
              >
                Sign in to analyze <ArrowRight className="w-4 h-4" />
              </button>
            </div>

            {/* Ecosystem Research Search Engine */}
            <div
              className={`border rounded-[32px] p-6 space-y-4 ${
                isLight
                  ? "bg-white border-[#d6e3da] text-[#1a2320] shadow-sm"
                  : "bg-[#070e0a] border-white/10 text-white"
              }`}
            >
              <div className="space-y-1">
                <span className="text-xs font-sans font-bold text-[#00D084] uppercase tracking-widest">
                  Ecosystem Research
                </span>
                <h4 className="text-base font-sans font-bold tracking-[-0.04em]">
                  Search inside My EV Services content:
                </h4>
                <p className={`text-[11px] font-sans font-light ${isLight ? "text-[#607267]" : "text-white/50"}`}>
                  Search webinars, updates, services, and store.
                </p>
              </div>

              <form onSubmit={handleResearchSubmit} className="space-y-3">
                <div className="relative">
                  <Search className="w-4 h-4 text-[#00D084] absolute left-3.5 top-3.5" />
                  <input
                    type="text"
                    placeholder="Search updates, webinars, parts..."
                    value={researchQuery}
                    onChange={(e) => setResearchQuery(e.target.value)}
                    className={`w-full border rounded-full pl-10 pr-3.5 py-2.5 text-xs font-sans focus:outline-none focus:border-[#00D084] ${
                      isLight
                        ? "bg-[#f2f7f4] border-[#c5d6ca] text-[#1a2320] placeholder-[#607267]"
                        : "bg-[#020403] border-white/15 text-white placeholder-white/40"
                    }`}
                  />
                </div>
                <button
                  type="submit"
                  className={`w-full py-2.5 rounded-full text-xs font-sans font-bold uppercase tracking-wider transition-all cursor-pointer ${
                    isLight
                      ? "bg-[#e8f2eb] hover:bg-[#d5e6da] text-[#1a2320]"
                      : "bg-white/10 hover:bg-white/20 text-white"
                  }`}
                >
                  Search Ecosystem
                </button>
              </form>
            </div>

            {/* Promoted Recommendations */}
            <div
              className={`border rounded-[32px] p-6 space-y-4 ${
                isLight
                  ? "bg-white border-[#d6e3da] text-[#1a2320] shadow-sm"
                  : "bg-[#070e0a] border-white/10 text-white"
              }`}
            >
              <div className="space-y-1">
                <span className="text-xs font-sans font-bold text-[#00D084] uppercase tracking-widest">
                  Promoted
                </span>
                <h4 className="text-base font-sans font-bold tracking-[-0.04em]">
                  Services and parts we recommend right now.
                </h4>
              </div>

              <div className="space-y-3 text-xs">
                {/* Promoted Item 1 */}
                <div
                  className={`p-4 rounded-2xl border space-y-1 hover:border-[#00D084]/60 transition-colors ${
                    isLight ? "bg-[#f2f7f4] border-[#d6e3da]" : "bg-[#020503] border-white/10"
                  }`}
                >
                  <div className="font-sans font-bold tracking-[-0.03em] text-sm">
                    Battery Health Check
                  </div>
                  <p className={`text-xs font-sans ${isLight ? "text-[#607267]" : "text-white/60"}`}>
                    Diagnostics + report built for EV reliability.
                  </p>
                  <Link
                    to="/find-services"
                    className="text-[#00D084] font-sans font-bold text-[11px] hover:underline inline-flex items-center gap-1 pt-1"
                  >
                    Book Diagnostic <ArrowRight className="w-3 h-3" />
                  </Link>
                </div>

                {/* Promoted Item 2 */}
                <div
                  className={`p-4 rounded-2xl border space-y-1 hover:border-[#00D084]/60 transition-colors ${
                    isLight ? "bg-[#f2f7f4] border-[#d6e3da]" : "bg-[#020503] border-white/10"
                  }`}
                >
                  <div className="font-sans font-bold tracking-[-0.03em] text-sm">
                    Charging essentials
                  </div>
                  <p className={`text-xs font-sans ${isLight ? "text-[#607267]" : "text-white/60"}`}>
                    Charger + cable bundles for daily use.
                  </p>
                  <Link
                    to="/store"
                    className="text-[#00D084] font-sans font-bold text-[11px] hover:underline inline-flex items-center gap-1 pt-1"
                  >
                    View Bundles <ArrowRight className="w-3 h-3" />
                  </Link>
                </div>
              </div>
            </div>

          </div>

        </div>
      </section>

      {/* =========================================================================
          5. FIND EV SERVICE NEAR YOU BANNER
         ========================================================================= */}
      <section className="py-12 px-6 max-w-7xl mx-auto text-left">
        <div
          className={`border-2 border-[#00D084] rounded-[32px] p-8 md:p-12 relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-8 ${
            isLight ? "bg-[#00D084]/20 text-[#1a2320]" : "bg-[#00D084]/15 text-white"
          }`}
        >
          <div className="space-y-2 max-w-2xl">
            <span className="text-xs font-sans font-bold uppercase tracking-widest text-[#00D084] block">
              NATIONAL NETWORK
            </span>
            <h2 className="text-3xl sm:text-4xl font-sans font-bold tracking-[-0.04em]">
              Find EV Service Near You
            </h2>
            <p className={`text-sm sm:text-base font-sans font-light ${isLight ? "text-[#3a4841]" : "text-white/80"}`}>
              Browse service centres across India by city and locality.
            </p>
          </div>

          <Link
            to="/find-services"
            className="px-8 py-4 rounded-full bg-[#00D084] text-[#020403] text-xs font-sans font-black uppercase tracking-widest hover:bg-[#00e08f] transition-all shrink-0 cursor-pointer shadow-md"
          >
            Explore Service Network
          </Link>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
}
