import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useEffect, useMemo } from "react";
import { Nav } from "../components/Nav";
import { Footer } from "../components/Footer";
import {
  Search,
  BookOpen,
  Sparkles,
  Zap,
  BatteryCharging,
  Wrench,
  ShieldCheck,
  ArrowRight,
  UserCheck,
  SlidersHorizontal,
  MapPin,
  Clock,
  ChevronRight,
  Tag,
  Star,
  Flame,
  Bot,
  Layers,
  FilterX,
} from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/blog")({
  component: BlogPage,
});

interface BlogPost {
  id: string;
  title: string;
  category: string;
  readTime: string;
  date: string;
  excerpt: string;
  author: string;
  img: string;
  featured?: boolean;
}

const CATEGORIES = [
  "All",
  "Maintenance",
  "Troubleshooting",
  "Battery Care",
  "How-to Guides",
  "Tips & Tricks",
];

const SAMPLE_POSTS: BlogPost[] = [
  {
    id: "post-1",
    title: "5 Critical Signs Your EV Battery Cell Needs Active Balancing",
    category: "Battery Care",
    readTime: "5 min read",
    date: "Aug 14, 2026",
    excerpt: "Learn how capacity drift occurs in lithium-ion battery packs and how Autobot OS cell-level balancing restores original range.",
    author: "Autobot Technical Team",
    img: "https://images.unsplash.com/photo-1558441719-2347b7341ed2?w=800&auto=format&fit=crop&q=80",
    featured: true,
  },
  {
    id: "post-2",
    title: "How to Maximize Ola & Ather Range During Peak Indian Summers",
    category: "Tips & Tricks",
    readTime: "4 min read",
    date: "Aug 10, 2026",
    excerpt: "Essential thermal management practices to prevent BMS throttling and preserve battery health in 40°C+ ambient temperatures.",
    author: "Rajesh Kumar, Senior EV Diagnostics",
    img: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: "post-3",
    title: "Step-by-Step Guide: Troubleshooting BLDC Hub Motor Noise",
    category: "Troubleshooting",
    readTime: "7 min read",
    date: "Aug 05, 2026",
    excerpt: "Diagnosing bearing wear, hall sensor misalignment, and phase wire shorts before controller breakdown occurs.",
    author: "Autobot Technical Team",
    img: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: "post-4",
    title: "EV Periodic Maintenance Checklist: 32 Points Every Owner Should Know",
    category: "Maintenance",
    readTime: "6 min read",
    date: "Jul 28, 2026",
    excerpt: "From brake fluid moisture testing to CAN-bus diagnostic error code scans: a complete guide to preventive EV care.",
    author: "Priya Sharma, Lead Quality Audit",
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: "post-5",
    title: "How to Read BMS Diagnostic Telemetry Reports Like a Pro",
    category: "How-to Guides",
    readTime: "5 min read",
    date: "Jul 20, 2026",
    excerpt: "Understanding delta voltage, cell internal resistance (mΩ), and state-of-health (SOH) graphs generated by AI diagnostic hubs.",
    author: "Autobot Technical Team",
    img: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80",
  },
];

function BlogPage() {
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [researchQuery, setResearchQuery] = useState("");

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const filteredPosts = useMemo(() => {
    return SAMPLE_POSTS.filter((post) => {
      const matchesCategory =
        selectedCategory === "All" || post.category === selectedCategory;
      const query = searchQuery.toLowerCase().trim();
      const matchesSearch =
        !query ||
        post.title.toLowerCase().includes(query) ||
        post.excerpt.toLowerCase().includes(query) ||
        post.category.toLowerCase().includes(query);

      return matchesCategory && matchesSearch;
    });
  }, [selectedCategory, searchQuery]);

  const clearFilters = () => {
    setSelectedCategory("All");
    setSearchQuery("");
  };

  const handleResearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!researchQuery) return;
    toast.success(`Searching ecosystem for "${researchQuery}"...`);
  };

  return (
    <div className="min-h-screen bg-[#020403] text-white selection:bg-[#00D084] selection:text-black font-serif overflow-x-hidden">
      {/* Navigation */}
      <Nav />

      {/* =========================================================================
          1. HERO HEADER SECTION
         ========================================================================= */}
      <section className="relative pt-36 pb-20 px-6 border-b border-white/10 bg-gradient-to-b from-[#080e0b] to-[#020403] overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[700px] h-[700px] bg-[#00D084]/10 rounded-full blur-[180px] pointer-events-none" />

        <div className="max-w-5xl mx-auto text-center relative z-10 space-y-6">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#00D084]/40 bg-[#00D084]/15 px-4 py-1.5 text-[11px] font-bold uppercase tracking-widest text-[#00D084]">
            <Sparkles className="w-3.5 h-3.5" />
            Expert Insights & Data-Driven Advice
          </div>

          <h1 className="text-4xl sm:text-6xl md:text-7xl font-serif font-black tracking-tight text-white leading-[1.08]">
            EV Care Blog <br />
            <span className="text-[#00D084]">for Indian Riders</span>
          </h1>

          <p className="text-base sm:text-lg text-white/70 font-serif font-normal leading-relaxed max-w-2xl mx-auto">
            Practical tips, troubleshooting guides, and expert insights from our certified EV service technicians across India.
          </p>

          <div className="pt-2 flex justify-center">
            <a
              href="#blog-archive"
              className="px-8 py-3.5 rounded-full border border-white/20 text-white text-xs font-serif font-bold uppercase tracking-widest hover:bg-white/10 transition-all cursor-pointer"
            >
              View Archive
            </a>
          </div>
        </div>
      </section>

      {/* =========================================================================
          2. MAIN CONTENT GRID (ARTICLES & AI ANALYZER SIDEBAR)
         ========================================================================= */}
      <section id="blog-archive" className="py-20 px-6 max-w-7xl mx-auto font-serif">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          
          {/* Main Articles Area (8 cols) */}
          <div className="lg:col-span-8 space-y-8">
            
            {/* Category Filter Pills & Search Input */}
            <div className="space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div className="flex flex-wrap items-center gap-2">
                  {CATEGORIES.map((cat) => (
                    <button
                      key={cat}
                      onClick={() => setSelectedCategory(cat)}
                      className={`px-4 py-2 rounded-full text-xs font-serif font-bold transition-all cursor-pointer border ${
                        selectedCategory === cat
                          ? "bg-[#00D084] text-[#020403] border-[#00D084]"
                          : "bg-[#050907] text-white/70 border-white/10 hover:border-white/20 hover:text-white"
                      }`}
                    >
                      {cat}
                    </button>
                  ))}
                </div>

                <div className="text-xs font-serif text-white/50">
                  All Articles ({filteredPosts.length})
                </div>
              </div>

              {/* Instant Search Bar */}
              <div className="relative">
                <Search className="w-4 h-4 text-[#00D084] absolute left-3.5 top-3.5" />
                <input
                  type="text"
                  placeholder="Filter articles by keyword (e.g., BMS, Ather, Motor, Noise)..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full bg-[#050907] border border-white/15 rounded-2xl pl-10 pr-4 py-3 text-xs text-white font-serif focus:outline-none focus:border-[#00D084]"
                />
              </div>
            </div>

            {/* Articles Grid or Empty State */}
            {filteredPosts.length > 0 ? (
              <div className="space-y-6">
                {filteredPosts.map((post) => (
                  <article
                    key={post.id}
                    className="bg-[#050907] border border-white/10 hover:border-[#00D084]/40 rounded-3xl p-6 transition-all duration-300 group flex flex-col md:flex-row gap-6 items-start"
                  >
                    <img
                      src={post.img}
                      alt={post.title}
                      className="w-full md:w-48 h-36 object-cover rounded-2xl shrink-0 group-hover:scale-102 transition-transform duration-500"
                    />

                    <div className="space-y-3 flex-1">
                      <div className="flex items-center justify-between text-xs font-serif text-white/50">
                        <span className="text-[#00D084] font-bold uppercase tracking-wider">
                          {post.category}
                        </span>
                        <span>{post.date} • {post.readTime}</span>
                      </div>

                      <h3 className="text-xl font-serif font-bold text-white group-hover:text-[#00D084] transition-colors leading-snug">
                        {post.title}
                      </h3>

                      <p className="text-xs text-white/60 font-serif leading-relaxed">
                        {post.excerpt}
                      </p>

                      <div className="flex items-center justify-between pt-2">
                        <span className="text-[11px] text-white/40 italic font-serif">
                          By {post.author}
                        </span>
                        <button
                          onClick={() => toast.info(`Opening article: "${post.title}"`)}
                          className="text-xs font-serif font-bold text-[#00D084] hover:underline flex items-center gap-1 cursor-pointer"
                        >
                          Read Article <ChevronRight className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>
                  </article>
                ))}
              </div>
            ) : (
              /* No Articles Found State (as requested) */
              <div className="bg-[#050907] border border-white/10 rounded-3xl p-12 text-center space-y-4">
                <div className="w-12 h-12 rounded-full bg-white/5 border border-white/10 flex items-center justify-center mx-auto text-white/40">
                  <FilterX className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-serif font-bold text-white">
                  No articles found matching your criteria.
                </h3>
                <p className="text-xs text-white/50 font-serif">
                  Try clearing your category filters or search query to view all technical guides.
                </p>
                <button
                  onClick={clearFilters}
                  className="px-6 py-2.5 rounded-full bg-[#00D084] text-[#020403] text-xs font-serif font-bold uppercase tracking-wider hover:bg-[#00e08f] transition-all cursor-pointer"
                >
                  Clear filters
                </button>
              </div>
            )}
          </div>

          {/* Sidebar Area (4 cols) */}
          <div className="lg:col-span-4 space-y-8">
            
            {/* My EV Services AI Analyzer Card (Requested) */}
            <div className="bg-[#050c08] border-2 border-[#00D084]/40 rounded-3xl p-6 text-left space-y-4 relative overflow-hidden font-serif">
              <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#00D084]/15 border border-[#00D084]/30 text-[10px] font-bold text-[#00D084] uppercase tracking-widest">
                <Bot className="w-3.5 h-3.5" /> Internal ecosystem only
              </div>

              <div className="space-y-1">
                <span className="text-xs font-serif font-bold text-white/50 block">My EV Services AI</span>
                <h3 className="text-2xl font-serif font-extrabold text-white">Analyze your vehicle</h3>
              </div>

              <p className="text-xs text-white/70 font-serif font-light leading-relaxed">
                If you’re signed in, pick your saved EV and get a weakness checklist.
              </p>

              <button
                onClick={() => toast.info("Opening AI vehicle analysis login flow...")}
                className="w-full py-3 rounded-xl bg-[#00D084] text-[#020403] text-xs font-serif font-extrabold uppercase tracking-widest hover:bg-[#00e08f] transition-all cursor-pointer flex items-center justify-center gap-2"
              >
                Sign in to analyze <ArrowRight className="w-4 h-4" />
              </button>
            </div>

            {/* Ecosystem Research Search Engine (Requested) */}
            <div className="bg-[#050907] border border-white/10 rounded-3xl p-6 text-left space-y-4 font-serif">
              <div className="space-y-1">
                <span className="text-xs font-serif font-bold text-[#00D084] uppercase tracking-widest">Ecosystem Research</span>
                <h4 className="text-base font-serif font-bold text-white">Search inside My EV Services content:</h4>
                <p className="text-[11px] text-white/50 font-serif">
                  Search webinars, updates, services, and store.
                </p>
              </div>

              <form onSubmit={handleResearchSubmit} className="space-y-3">
                <div className="relative">
                  <Search className="w-4 h-4 text-[#00D084] absolute left-3.5 top-3.5" />
                  <input
                    type="text"
                    placeholder="Search updates, webinars, parts..."
                    value={researchQuery}
                    onChange={(e) => setResearchQuery(e.target.value)}
                    className="w-full bg-[#020403] border border-white/15 rounded-xl pl-10 pr-3.5 py-2.5 text-xs text-white font-serif focus:outline-none focus:border-[#00D084]"
                  />
                </div>
                <button
                  type="submit"
                  className="w-full py-2.5 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-serif font-bold uppercase tracking-wider transition-all cursor-pointer"
                >
                  Search Ecosystem
                </button>
              </form>
            </div>

            {/* Promoted Recommendations (Requested) */}
            <div className="bg-[#050907] border border-white/10 rounded-3xl p-6 text-left space-y-4 font-serif">
              <div className="space-y-1">
                <span className="text-xs font-serif font-bold text-[#00D084] uppercase tracking-widest">Promoted</span>
                <h4 className="text-base font-serif font-bold text-white">Services and parts we recommend right now.</h4>
              </div>

              <div className="space-y-3 text-xs">
                {/* Promoted Item 1 */}
                <div className="p-4 rounded-2xl bg-[#020503] border border-white/10 space-y-1 hover:border-[#00D084]/40 transition-colors">
                  <div className="font-bold text-white text-sm">Battery Health Check</div>
                  <p className="text-white/60 text-xs">Diagnostics + report built for EV reliability.</p>
                  <Link
                    to="/find-services"
                    className="text-[#00D084] font-bold text-[11px] hover:underline inline-flex items-center gap-1 pt-1"
                  >
                    Book Diagnostic <ArrowRight className="w-3 h-3" />
                  </Link>
                </div>

                {/* Promoted Item 2 */}
                <div className="p-4 rounded-2xl bg-[#020503] border border-white/10 space-y-1 hover:border-[#00D084]/40 transition-colors">
                  <div className="font-bold text-white text-sm">Charging essentials</div>
                  <p className="text-white/60 text-xs">Charger + cable bundles for daily use.</p>
                  <Link
                    to="/store"
                    className="text-[#00D084] font-bold text-[11px] hover:underline inline-flex items-center gap-1 pt-1"
                  >
                    View Bundles <ArrowRight className="w-3 h-3" />
                  </Link>
                </div>
              </div>
            </div>

          </div>

        </div>
      </section>

      {/* =========================================================================
          3. FIND EV SERVICE NEAR YOU BANNER
         ========================================================================= */}
      <section className="py-20 px-6 max-w-7xl mx-auto font-serif">
        <div className="bg-[#00D084]/15 border-2 border-[#00D084] rounded-3xl p-8 md:p-12 relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-8">
          <div className="space-y-2 max-w-2xl">
            <span className="text-xs font-serif font-bold uppercase tracking-widest text-[#00D084] block">
              NATIONAL NETWORK
            </span>
            <h2 className="text-3xl sm:text-4xl font-serif font-extrabold text-white">
              Find EV Service Near You
            </h2>
            <p className="text-sm sm:text-base text-white/80 font-serif font-light">
              Browse service centres across India by city and locality.
            </p>
          </div>

          <Link
            to="/find-services"
            className="px-8 py-4 rounded-full bg-[#00D084] text-[#020403] text-xs font-serif font-black uppercase tracking-widest hover:bg-[#00e08f] transition-all shrink-0 cursor-pointer"
          >
            Explore Service Network
          </Link>
        </div>
      </section>

      {/* =========================================================================
          4. FOOTER CALLOUT BANNER
         ========================================================================= */}
      <section className="py-24 px-6 border-t border-white/10 bg-gradient-to-b from-[#080d0a] to-[#020403] font-serif text-center">
        <div className="max-w-4xl mx-auto space-y-6">
          <span className="text-xs font-serif font-bold uppercase tracking-widest text-[#00D084]">
            India's #1 EV Service Network
          </span>

          <h2 className="text-4xl sm:text-6xl font-serif font-black text-white tracking-tight leading-tight">
            Your EV Deserves <span className="text-[#00D084]">Expert Care</span>
          </h2>

          <p className="text-base sm:text-lg text-white/70 font-serif font-light max-w-2xl mx-auto">
            Certified technicians. Doorstep service. Genuine parts.
          </p>

          <div className="flex flex-wrap items-center justify-center gap-4 pt-4">
            <button
              onClick={() => toast.success("Booking system opened!")}
              className="px-8 py-4 rounded-full bg-[#00D084] text-[#020403] text-xs font-serif font-black uppercase tracking-widest hover:bg-[#00e08f] transition-all cursor-pointer"
            >
              Book a Service
            </button>
            <Link
              to="/store"
              className="px-8 py-4 rounded-full border border-white/20 text-white text-xs font-serif font-bold uppercase tracking-widest hover:bg-white/10 transition-all cursor-pointer"
            >
              Explore Parts
            </Link>
            <Link
              to="/find-services"
              className="px-8 py-4 rounded-full bg-white/10 border border-white/20 text-white text-xs font-serif font-bold uppercase tracking-widest hover:bg-white/20 transition-all cursor-pointer"
            >
              Find Centers Near You
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
}
