import { Review } from "./types";

// Import sample asset images if needed, but since we are a clean luxury portfolio, 
// we will use beautiful high-res Unsplash placeholders to look stunning.
export const dummyReviews: Review[] = [
  // Column 1 Reviews
  {
    id: "1",
    name: "Aidan Vance",
    role: "Director of Fleet Operations",
    company: "VeloStream Logistics",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=80&q=80",
    rating: 5,
    review: "Integrating VoltRide's multi-brand ecosystem was the single most impactful decision we made this fiscal year. Our technician dispatch delays were cut down to zero, and the real-time telemetry updates have completely transformed our maintenance lifecycle. Absolutely stellar engineering.",
  },
  {
    id: "2",
    name: "Elena Rostova",
    role: "Head of Infrastructure",
    company: "NeoGrid Transit",
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
    review: "Stunning deployment. The custom lab configuration allowed us to test and validate over 50 charging scenarios in under 48 hours. A Masterclass in developer UX.",
    date: "June 2026",
    industry: "Electric Mobility",
  },
  {
    id: "3",
    name: "Julian Kross",
    role: "Chief Executive Officer",
    company: "Apex Charging Solutions",
    rating: 5,
    review: "THE CHASSIS DESIGN AND DRIVETRAIN CALIBRATION DELIVER AN UNCOMPROMISING DRIVING DYNAMIC THAT REDEFINES URBAN LUXURY.",
  },
  {
    id: "4",
    name: "Marcus Vance",
    role: "Operations Lead",
    company: "Voltaic Delivery Corp",
    story: {
      before: "Manual parts inventory verification taking up to 3 hours per daily shift",
      after: "Instant QR-code scanning with auto-replenishment logistics synchronization",
      metric: "+320%",
      metricLabel: "Operational Efficiency",
    },
    metrics: "Efficiency",
  },
  {
    id: "5",
    name: "Sarah Chen",
    role: "Lead Systems Architect",
    company: "Helix Automotive",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    companyLogo: "https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?auto=format&fit=crop&w=80&q=80",
    rating: 5,
    review: "We built our custom telematics pipeline on top of the VoltRide API. The developer experience is second to none. Documentation is impeccable, and the performance characteristics under heavy payloads are extremely consistent.",
  },
  {
    id: "6",
    name: "David Sterling",
    role: "Managing Director",
    company: "Sterling Luxury Group",
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80",
    review: "The visual aesthetic of the flagship model combined with the seamless charging network software represents the absolute pinnacle of modern EV luxury.",
    date: "April 2026",
    industry: "Premium Lifestyle",
  },

  // Column 2 Reviews
  {
    id: "7",
    name: "Sophia Martinez",
    role: "VP of Sustainability",
    company: "Ecoline Transport",
    story: {
      before: "Estimated 400 tons of CO2 offset annually using mixed combustion fleets",
      after: "Verified 2,400 tons offset via fully-integrated solar and smart battery grids",
      metric: "2,400t",
      metricLabel: "Carbon Offset",
    },
    metrics: "Sustainability",
  },
  {
    id: "8",
    name: "Nicholas Drake",
    role: "Creative Director",
    company: "Mono Studio",
    rating: 5,
    review: "A SIMPLIFIED, INTUITIVE INTERFACE THAT CONVERTED COMPLEX GRID TELEMETRY DATA INTO AN INTERACTIVE WORKFLOW THAT ANYONE CAN MASTER.",
  },
  {
    id: "9",
    name: "Clara Oswald",
    role: "Franchise Owner",
    company: "Zenith Services Munich",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=80&q=80",
    rating: 5,
    review: "The technician application changed everything for us. In-app navigation, QR inventory lookup, and digital job signatures completely eliminated our administrative overhead. Our technicians are happier, and job execution times dropped by 30%.",
  },
  {
    id: "10",
    name: "Lucas Hedges",
    role: "Principal Engineer",
    company: "Voltlabs Inc",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80",
    review: "Testing cell density scaling and thermal dissipation properties inside the VoltRide Sandbox was incredibly fast. Highly recommended product.",
    date: "May 2026",
    industry: "Energy Storage",
  },
  {
    id: "11",
    name: "Hana Kobayashi",
    role: "Fleet Controller",
    company: "Tokio Logistics",
    rating: 5,
    review: "ACCELERATED TRANSITION TO ZERO-EMISSION TARGETS WITH PREDICTIVE MAINTENANCE LOGIC THAT DETECTS ANOMALIES BEFORE THEY CAUSE DOWNTIME.",
  },
  {
    id: "12",
    name: "Arthur Pendragon",
    role: "President",
    company: "Pendragon Chargers",
    story: {
      before: "Average response time of 90 minutes for onsite charger debugging",
      after: "Automated remote OTA updates and diagnostic routing in under 12 minutes",
      metric: "-86%",
      metricLabel: "Response Latency",
    },
    metrics: "Response Time",
  },

  // Column 3 Reviews
  {
    id: "13",
    name: "Nate Robinson",
    role: "VP of Engineering",
    company: "Urban Grid Systems",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
    companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=80&q=80",
    rating: 5,
    review: "We compared four major EV developer tools before choosing VoltRide. Their API is by far the most stable, secure, and performant. The webhooks integration alone saved our engineering team weeks of custom development.",
  },
  {
    id: "14",
    name: "Isabella Rossi",
    role: "Director of Design",
    company: "Milano EV Design",
    image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80",
    review: "Exquisite visual language, high-quality finishes, and digital controls that feel tactile and expensive. Absolutely brilliant.",
    date: "July 2026",
    industry: "Industrial Design",
  },
  {
    id: "15",
    name: "Tariq Al-Fayed",
    role: "Operations Manager",
    company: "Gulf Energy Grid",
    rating: 5,
    review: "THE SCALABILITY OF THE SUN-TO-WATT SOLAR INFRASTRUCTURE HAS ALLOWED US TO CHARGE 800+ VEHICLES DAILY COMPLETELY OFF-GRID.",
  },
  {
    id: "16",
    name: "Amara Okeke",
    role: "Head of Operations",
    company: "Lagos Electric Express",
    story: {
      before: "Job acceptance rates hover around 68% due to scheduling conflicts",
      after: "Optimized technician route-matching boosts acceptance to 94% average",
      metric: "94%",
      metricLabel: "Job Acceptance",
    },
    metrics: "Acceptance Rate",
  },
  {
    id: "17",
    name: "Oliver Quinn",
    role: "Managing Director",
    company: "Quinn Logistics",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80",
    companyLogo: "https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?auto=format&fit=crop&w=80&q=80",
    rating: 5,
    review: "We consolidated our entire fleet service network into the My EV Services console. Having automated ticket dispatching and parts ordering in one dashboard completely transformed our profitability margins.",
  },
  {
    id: "18",
    name: "Fiona Gallagher",
    role: "Director of Maintenance",
    company: "SouthSide Transit",
    image: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=800&q=80",
    review: "Having QR code inventory built right into the technician app solved our parts leakage problem. Every single piece is tracked from warehouse to the wheel.",
    date: "March 2026",
    industry: "Fleet Maintenance",
  }
];
